# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: upload
on:
  workflow_dispatch:

env:
  CI: ""

defaults:
  run:
    shell: pwsh

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install all packages
        run: npm install

      - name: Install the json package
        run: sudo npm install -g json

      - name: Modify homepage in package.json
        run: json -I -f package.json -e 'this.homepage="https://radekvym.github.io/bezel-more"'

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
